// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcfSJtc5naM5rp4ZqzGFX29c_TWqRpcM8',
    appId: '1:70535792913:web:480d7dbcc2b884d6f4a4b0',
    messagingSenderId: '70535792913',
    projectId: 'pawsaviour-87713',
    authDomain: 'pawsaviour-87713.firebaseapp.com',
    storageBucket: 'pawsaviour-87713.firebasestorage.app',
    measurementId: 'G-Z42X4525KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJPsTDNX9EFJipSnF-nHJR72hju57_n1w',
    appId: '1:70535792913:android:135fafc33ea2bf93f4a4b0',
    messagingSenderId: '70535792913',
    projectId: 'pawsaviour-87713',
    storageBucket: 'pawsaviour-87713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxPlAuiq7MCfo3a9MGGEjjax0fnJe2nYQ',
    appId: '1:70535792913:ios:6554bcde7be98087f4a4b0',
    messagingSenderId: '70535792913',
    projectId: 'pawsaviour-87713',
    storageBucket: 'pawsaviour-87713.firebasestorage.app',
    iosBundleId: 'com.example.animalRescueAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxPlAuiq7MCfo3a9MGGEjjax0fnJe2nYQ',
    appId: '1:70535792913:ios:6554bcde7be98087f4a4b0',
    messagingSenderId: '70535792913',
    projectId: 'pawsaviour-87713',
    storageBucket: 'pawsaviour-87713.firebasestorage.app',
    iosBundleId: 'com.example.animalRescueAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcfSJtc5naM5rp4ZqzGFX29c_TWqRpcM8',
    appId: '1:70535792913:web:c383489494f68143f4a4b0',
    messagingSenderId: '70535792913',
    projectId: 'pawsaviour-87713',
    authDomain: 'pawsaviour-87713.firebaseapp.com',
    storageBucket: 'pawsaviour-87713.firebasestorage.app',
    measurementId: 'G-V04P54LVFS',
  );
}
